version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Set JVM heap size (adjust as needed)
    ports:
      - "9200:9200" # Elasticsearch API
      - "9300:9300" # Elasticsearch transport
    volumes:
      - esdata:/usr/share/elasticsearch/data # Persistent storage for Elasticsearch

volumes:
  esdata:
    driver: local
